### ISSUE TITLE
Invalid Pose issue

### ISSUE THREAD

**Issue by harjatinsingh** [mdalal2020/sawyer_control#12]
Inverse Kinematics fails quite often when using position control and throws the following error, is this usual ?

> [INFO] [1548575100.506818]: INVALID POSE - No Valid Joint Solution Found.

This even happens when the desired position is more than 0.5 from the robot. Do I need to change `UPDATE_HZ = 20` in base_config.py in case of position control ? 

P.S. The only major change I am making is that I am fixing the gripper orientation instead of it coming from a learnt policy.

**Comment by shikharbahl** [comment]
This usually happens when the inverse kinematics proposes a solution that is difficult to achieve. One way around this to produce smaller actions. What is the mean length of the actions (in each dimension) and could you try sending 0 actions and then gradually increase the size.

**Comment by harjatinsingh** [comment]
Mean length is 0.05 in each dimension. I thought that was quite small already, I will try with 0 action and then increasing though.

**Comment by mihdalal** [comment]
I'm going to close this now since it has been inactive for over a month.
